USE_PUNCTUATION = True

INACCURACY_WEIGHT = 20
SFB_WEIGHT = 4
FINGER_FREQ_WEIGHT = 2
REDIRECT_WEIGHT = 1.5
DISCOMFORT_WEIGHT = 1.5
SFS_WEIGHT = 1.5

# Discomfort
PINKY_ABOVE_RING = 3
PINKY_ABOVE_MIDDLE = 2.6
RING_ABOVE_MIDDLE = 1

# Redirect
BAD_REDIRECT = 1.3

# SFB SFS
SFB_SFS_DIFF_KEY_PENALTY = 3 
SFB_SFS_PINKY_PUNISHMENT = 3

PINKY_WEIGHT = 1.5
RING_WEIGHT = 3.6
MIDDLE_WEIGHT = 4.8
INDEX_WEIGHT = 5.5
weight_sum = PINKY_WEIGHT + RING_WEIGHT + MIDDLE_WEIGHT + INDEX_WEIGHT

PINKY_FREQ = PINKY_WEIGHT / (2 * weight_sum)
RING_FREQ = RING_WEIGHT / (2 * weight_sum)
MIDDLE_FREQ = MIDDLE_WEIGHT / (2 * weight_sum)
INDEX_FREQ = INDEX_WEIGHT / (2 * weight_sum)
GOAL_FINGER_FREQ = [
    [0.815 * PINKY_FREQ, 0.815 * RING_FREQ, 0.815 * MIDDLE_FREQ, 0.815 * INDEX_FREQ],
    [1.185 * INDEX_FREQ, 1.185 * MIDDLE_FREQ, 1.185 * RING_FREQ, 1.185 * PINKY_FREQ],
]  # Left should have ~40% to account for space key addition (18.5%)
assert abs(sum(key for hand in GOAL_FINGER_FREQ for key in hand)) - 1 < 0.00001
