from enum import Enum

class InaccuracyMode(Enum):
    IGNORE_FIRST = "Ignore First"
    IGNORE_LAST = "Ignore Last"
    ONLY_FIRST = "Only First"
    ONLY_LAST = "Only Last"
    MIDDLE = "Middle"
    ALL = "All"


PRINT = False
MODE = InaccuracyMode.IGNORE_FIRST
USE_PUNCTUATION = True
NUM_MAGIC = 0
INACCURACY_WEIGHT = 1
SFB_WEIGHT = 0.1
DISCOMFORT_WEIGHT = 0.025
SFS_WEIGHT = 0.025
REDIRECT_WEIGHT = 0.025
FINGER_FREQ_WEIGHT = 0.01

# Discomfort
PINKY_ABOVE_RING = 3
PINKY_ABOVE_MIDDLE = 2.6
RING_ABOVE_MIDDLE = 1

# Redirect
BAD_REDIRECT = 2

# SFB SFS
SFB_SFS_DIFF_KEY_PENALTY = 2
SFB_SFS_PINKY_PENALTY = 2.5

PINKY_WEIGHT = 1.5
RING_WEIGHT = 3.6
MIDDLE_WEIGHT = 4.8
INDEX_WEIGHT = 5.5

# From Oxeylyzer, pinky - 1%
PINKY_MAX = 0.08
RING_MAX = 0.14
MIDDLE_MAX = 0.2
INDEX_MAX = 0.2

GOAL_FINGER_MAX = [[PINKY_MAX, RING_MAX, MIDDLE_MAX, INDEX_MAX],[INDEX_MAX, MIDDLE_MAX, RING_MAX, PINKY_MAX]]

weight_sum = PINKY_WEIGHT + RING_WEIGHT + MIDDLE_WEIGHT + INDEX_WEIGHT

PINKY_FREQ = PINKY_WEIGHT / (2 * weight_sum)
RING_FREQ = RING_WEIGHT / (2 * weight_sum)
MIDDLE_FREQ = MIDDLE_WEIGHT / (2 * weight_sum)
INDEX_FREQ = INDEX_WEIGHT / (2 * weight_sum)

GOAL_FINGER_FREQ = [
    [PINKY_FREQ, RING_FREQ, MIDDLE_FREQ, INDEX_FREQ],
    [INDEX_FREQ, MIDDLE_FREQ, RING_FREQ, PINKY_FREQ],
]
# # Left should have ~45% to account for space key addition.
# # Non-split layouts still might prefer a higher right-side usage
# GOAL_FINGER_FREQ = [
#     [0.9 * PINKY_FREQ, 0.9 * RING_FREQ, 0.9 * MIDDLE_FREQ, 0.9 * INDEX_FREQ],
#     [1.1 * INDEX_FREQ, 1.1 * MIDDLE_FREQ, 1.1 * RING_FREQ, 1.1 * PINKY_FREQ],
# ]
assert abs(sum(key for hand in GOAL_FINGER_FREQ for key in hand)) - 1 < 0.00001


def settings_to_str(space: str = " ") -> str:
    return f"""Settings:
USE_PUNCTUATION = {USE_PUNCTUATION}

INACCURACY_WEIGHT = {INACCURACY_WEIGHT}
SFB_WEIGHT = {SFB_WEIGHT}
REDIRECT_WEIGHT = {REDIRECT_WEIGHT}
DISCOMFORT_WEIGHT = {DISCOMFORT_WEIGHT}
SFS_WEIGHT = {SFS_WEIGHT}
FINGER_FREQ_WEIGHT = {FINGER_FREQ_WEIGHT}

Discomfort:
{space}PINKY_ABOVE_RING = {PINKY_ABOVE_RING}
{space}PINKY_ABOVE_MIDDLE = {PINKY_ABOVE_MIDDLE}
{space}RING_ABOVE_MIDDLE = {RING_ABOVE_MIDDLE}

Redirect:
{space}BAD_REDIRECT = {BAD_REDIRECT}

SFB SFS:
{space}SFB_SFS_DIFF_KEY_PENALTY = {SFB_SFS_DIFF_KEY_PENALTY}
{space}SFB_SFS_PINKY_PENALTY = {SFB_SFS_PINKY_PENALTY}

Finger Frequencies:
{space}PINKY_WEIGHT = {PINKY_WEIGHT}
{space}RING_WEIGHT = {RING_WEIGHT}
{space}MIDDLE_WEIGHT = {MIDDLE_WEIGHT}
{space}INDEX_WEIGHT = {INDEX_WEIGHT}
{space}GOAL_FINGER_FREQ = [
    [{GOAL_FINGER_FREQ[0][0]:.5f}, {GOAL_FINGER_FREQ[0][1]:.5f}, {GOAL_FINGER_FREQ[0][2]:.5f}, {GOAL_FINGER_FREQ[0][3]:.5f}],
    [{GOAL_FINGER_FREQ[1][0]:.5f}, {GOAL_FINGER_FREQ[1][1]:.5f}, {GOAL_FINGER_FREQ[1][2]:.5f}, {GOAL_FINGER_FREQ[1][3]:.5f}],
]"""
